call_parentheses = 'None'
column_width = 120
# collapse_simple_statement = 'ConditionalOnly'  # Never, FunctionOnly, ConditionalOnly, Always
indent_type = 'Spaces'
indent_width = 2
line_endings = 'Unix'
quote_style = 'AutoPreferSingle'
