call_parentheses = 'None'
column_width = 160
collapse_simple_statement = 'Never'  # Never, FunctionOnly, ConditionalOnly, Always
indent_type = 'Spaces'
indent_width = 2
line_endings = 'Unix'
quote_style = 'AutoPreferSingle'
