##
## Keymaps
##

# Prefix Key
set -g prefix C-q
set -g escape-time 0          # escape delay (when doing prefix) default: 500ms
bind C-q send-prefix          # prefix + C-q (C-q x2) will send C-q to nested app.
unbind C-b

# "Clear screen"
bind \; send-keys C-l  # C-l is used by plugin vim-tmux-navigator

bind c new-window -c "#{pane_current_path}"  # new window, use current panes path
bind \" split-window -v -c "#{pane_current_path}"  # split vertically, use current panes path
bind \% split-window -h -c "#{pane_current_path}"  # split horizontally, use current panes path

# Vi keys in copy mode
setw -g mode-keys vi  # default: emacs, use vi-style key bindings in copy mode (leader and vim keys to navigate panes etc)
bind -T copy-mode-vi "v" send -X begin-selection
bind -T copy-mode-vi "y" send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane  # don"t exit copy mode when dragging with mouse


##
## Settings
##

set -g detach-on-destroy off  # whether to detach when a session is destroyed, or switch the client to another session if any exist
set -g base-index 1           # start indexing windows at 1 instead of 0
setw -g pane-base-index 1     # start indexing panes   at 1 instead of 0
set -g renumber-windows on    # renumber all windows when any window is closed
set -g allow-rename on        # default: off, automatic renaming of windows

# Status line
setw -g monitor-activity on   # default: off, whether an alert is triggered by activity
set -g focus-events on        # default: off, whether to send focus events to applications
set -g status-interval 5      # default: 15
set -g status-style           "fg=#1f1f1f bg=#335917"
set -g status-left            "#{?client_prefix,#[reverse],} #{session_name}  "  # default: [#{session_name}]
set -g status-left-length     100
set -g status-right            ""
setw -g window-status-current-style  reverse
setw -g window-status-activity-style "bg=#1e350e"  # default: reverse, style of windows in the status line with an activity alert
setw -g window-status-format         " #[bold]#{?window_zoomed_flag, ,}#{=|-24|\u2026;:pane_current_path}#[nobold] "
setw -g window-status-current-format " #[bold]#{?window_zoomed_flag, ,}#{=|-24|\u2026;:pane_current_path}#[nobold] "
