##
## Keymaps
##

# Prefix Key
set -g prefix C-s
set -g escape-time 0  # escape delay (when doing prefix) default: 500ms
bind C-s send-prefix  # prefix + C-s (C-s x2) will send C-s to nested app.
unbind C-b

# "Clear screen"
bind \; send-keys C-l  # C-l is used by plugin vim-tmux-navigator

bind \" split-window -v -c "#{pane_current_path}"  # split vertically, use current panes path
bind \% split-window -h -c "#{pane_current_path}"  # split horizontally, use current panes path

# Vi keys in copy mode
setw -g mode-keys vi  # default: emacs, use vi-style key bindings in copy mode (leader and vim keys to navigate panes etc)
bind -T copy-mode-vi "v" send -X begin-selection
bind -T copy-mode-vi "y" send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane  # don"t exit copy mode when dragging with mouse


##
## Settings
##

# True Color Support (run :checkhealth in nvim for tips)
set -g default-terminal "tmux-256color"        # tmux-256color | xterm-256color | screen-256color
set -ga terminal-overrides ",xterm*:Tc"        # true color
set -sa terminal-features ",xterm*:RGB"        # proper colors
set -ga terminal-features ",xterm*:usstyle"    # undercurl

set -g detach-on-destroy on   # whether to detach when a session is destroyed, or switch the client to another session if any exist
set -g mouse on               # mouse support, resize windows and select tabs
set -g base-index 1           # start indexing windows at 1 instead of 0
setw -g pane-base-index 1     # start indexing panes   at 1 instead of 0
set -g renumber-windows on    # renumber all windows when any window is closed
set -g allow-rename on        # default: off, automatic renaming of windows
set -g set-titles on          # allow tmux to set the terminal title
set -g set-titles-string "#W #{=|-24|\u2026;s|$HOME|~|:pane_current_path} #{session_alerts}"

# Status line
setw -g monitor-activity on   # default: off, whether an alert is triggered by activity
set -g focus-events on        # default: off, whether to send focus events to applications
set -g status-interval 5      # default: 15
set -g status-style                 "fg=#7c7d83 bg=#1f1f1f"
set -g status-left                  "#{?client_prefix,#[fg=#b1b1b1],} #{session_name}  "  # default: [#{session_name}]
set -g status-left-length           100
setw -g window-status-current-style  "fg=#b1b1b1"
setw -g window-status-activity-style reverse  # default: reverse, style of windows in the status line with an activity alert
setw -g window-status-format "#[bold]#{?window_zoomed_flag, ,}#W#[nobold] #{=|-24|\u2026;s|$HOME|~|:pane_current_path} "
setw -g window-status-current-format "#[bold]#{?window_zoomed_flag, ,}#W#[nobold] #{=|-24|\u2026;s|$HOME|~|:pane_current_path} "


##
## Plugins
##

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"        # basic tmux settings everyone can agree on
set -g @plugin "tmux-plugins/tmux-yank"            # yank support, tmux copying to system clipboard
set -g @plugin "christoomey/vim-tmux-navigator"    # navigate tmux and vim in the same way (requires same plugin in vim)

# Initialize Tmux plugin manager
run "~/.config/tmux/plugins/tpm/tpm"
